import { Pokemon } from "../pokemon/pokemon.component";

export const POKEMONS: Pokemon[] = [
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    },
    {
        cat : "pokemon",
        idPok: 1,
        id: 2,
        name : "Missingno",
        image : "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/MissingNo.svg/langfr-800px-MissingNo.svg.png",
        type1: "feu",
        type2: "plante",
        gen: 4,
        stade: 3,
        taille: 6,
        poids: 5,
        talent: [""]
    }
];